name: Python Tests and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Получение кода
        uses: actions/checkout@v4

      - name: Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Запуск тестов и расчёт покрытия
        run: |
          pytest -v test.py --cov=xml_parser_tool --cov-report=term --cov-report=json:coverage.json

      - name: Создание бейджа покрытия
        if: github.event_name == 'push'
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: coverage.svg
          coverage-summary-path: coverage.json

      - name: Сохранение обновлённого бейджа
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Автоматически обновить бейдж покрытия"
          add: "coverage.svg"